name: FamousGuilds
version: 1.0
description: ThumbsApply is a plugin that promotes you to a group via password.
authors: [Todkommt, Sinnoh]
website: http://www.famousserver.de

main: com.famousserver.FamousGuilds.FamousGuilds

commands:
  guild:
    usage: /guild <subcommand>
  g:
    usage: /guild <subcommand>
  famousguild:
    usage: /guild <subcommand>
  fg:
    usage: /guild <subcommand>